name: Build Project

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: |
          ls
          echo "Restoring dependencies..."
          cd KiloMart.Presentation
          dotnet restore  

      - name: Build the project
        run: |
          echo "Building the project..."
          dotnet build  

      - name: Publish the project
        run: |
          echo "Publishing the project..."  
          dotnet publish -c Release -o publish

      - name: Check build directory contents
        run: |
          echo "Checking build directory contents..."
          ls -R publish/  

      - name: Upload files
        run: |
          echo "Uploading files..."
          curl -u ramadan09514:aboabdallahramadan@1 -T 'publish/*' ftp://kilomart-001-site1.ptempurl.com/kilomartapi/
