stages:
  - build

build_project:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Restoring dependencies..."
    - cd Foam  
    - dotnet restore Foam.csproj  
    - echo "Building the project..."
    - dotnet build Foam.csproj 
    - echo "Publishing the project..."  
    - dotnet publish Foam.csproj -c Release -o puplish
    - echo "Checking build directory contents..."
    - ls -R puplish/  
    - echo "Uploading files..."
    - curl -u ramadan09514:aboabdallahramadan@1 -T 'puplish/*' ftp://kilomart-001-site1.ptempurl.com/kilomartapi/ \;
  only:
    - dev